package exceptionHandling;

public class ExceptionExample {
	 
	    public static void main(String[] args) {
	        try {
	            // Code that may throw an exception
	            int result = divide(10, 0);
	            System.out.println("Result: " + result);
	        } catch (ArithmeticException e) {
	            // Handling the exception
	            System.out.println("Exception caught: Division by zero is not allowed.");
	        }
	    }
	    
	    public static int divide(int a, int b) {
	        return a / b; // This may throw ArithmeticException
	    }
	}


